### ISSUE TITLE
Plugin broken

### ISSUE THREAD

**Issue by ekntrtmz** [agentejo/Auth0#1]
As examined with @pauloamgomes in the getcockpit discourse this addon is broken.
Until now the following to do list has been worked out:
- hardcoded lines need to be substituted from config.yaml
- auth0 lock library needs to be updated (to 11.x)
- docs net to be updated and clarified

I would try to fix it and make a pull request. I am happy about comments if I have forgotten to put something crucial on the to do list.

**Comment by aheinze** [comment]
sure, I'm waiting for the PR ;-)

**Comment by ekntrtmz** [comment]
#2

**Comment by joona** [comment]
@ekntrtmz fixed and currently maintained version of the plugin can be found from https://github.com/joona/CockpitCMS-Auth0
